## Lab Assignment 2 - Python for Spatial Analysis (230020257)


## Github Repository Link

https://github.com/BrodieHutcheson/Assignment2_Python_bh

## Lab 1: Python Basics

## 1.2 Create a script that calculates the average of a list of numbers

In this exercise I made list of numbers and then created a function that would calculate the average of the list. The function would take the list input, calculate the average and return the result. I then printed the result. 

In [2]:
def average(numbers):  
    return sum(numbers) / len(numbers)  # defines a function that calculates the avergae of a list of numbers

print(average([60, 45, 23, 53, 75]))  # prints the results

51.2


## 1.3 What's the purpose
In this exercise I described the purpose of the 1st 2 expressions in the code below



In [ ]:
import pandas as pd
import geopandas as gpd
dat = pd.read_csv('data/world_cities.csv')  ## Import CSV file
geom = gpd.points_from_xy(dat['lon'], dat['lat'])
geom = gpd.GeoSeries(geom)
dat = gpd.GeoDataFrame(dat, geometry = gpd.GeoSeries(geom), crs = 4326)
dat.to_file('output/world_cities.shp')      ## Export Shapefile

The first 2 expressions are used to import python libraries into the notebook. Pandas is used for working with tabular data and geopandas is used for working with geospatial data. As this code involvolves CSV files and shapefiles, it's useful to have both pandas and geopandas libraries so that we can work with different data types. 

## 1.4 Indentation
In this exercise I was given a code with incorrect indentation that I had to fix. Dogs = 0 was too far over to the right so I had to put it directly below the 1 expression to fix the indentation

In [3]:
name = 'Dave'
dogs = 0  # proper indentation means that "dogs" should be directly underneath the above expression as it's not part of the above function
print('My name is', name, 'and I own', dogs, 'dogs.')  # prints the string

My name is Dave and I own 0 dogs.


## 1.5 Strings
In this exercise I combined strings together and then combined a string with an integer as well

In [4]:
a = "Taco "  # string indicated by quotation marks
b = "time"
c = a + b  # combines the 2 strings
print(c)  # prints the results of the combined strings

Taco time


In [5]:
a = "Buckie"
b = "Thistle"
c = "are"
d = "number"
e = 1  # integer
strng1 = a + " " + b + " " + c + " " + d + " " + str(e)  # use str to turn the integer into a string so the code will run
print(strng1)  # prints the string

Buckie Thistle are number 1


## 1.6 Nested if conditions
In this exercise I fixed the indentation on a nested if stated and then created a code with several nested if conditions myself


In [6]:
season = "Winter"
temperature = 10

if season == "Winter":

    if temperature > 7:  # indentation required as its part of the above function
        print("No need for winter jacket!") 
         

    else:
        print("It might be cold! Wear a proper jacket!")

elif season == "Summer":

    if temperature > 20:
        print("It's warm! Time to wear shorts!")

    else:
        print("Well this is Finland, better wear long trousers!")
else:  # not part of above function so no indentation required
    print("Check the weather forecast!")

No need for winter jacket!


In [7]:
team = "Buckie Thistle"
standing = 7

if team == "Buckie Thistle":  # is the team Buckie Thistle

    if standing < 18:  # is 7 is less than 18 then print below statement
        print("Bottom of the league. Unlucky Rothes")

    else:
        print("Rothes fc and better than Buckie Thistle")

elif team == "Deveronvale fc":  # is the team Deveronvale

    if standing > 11:  # if standing is greater than 11 then print below statement
        print("Deveronvale fc are superior to the mighty Jags")
    else:
        print("Buckie Thistle can't be stopped")
else:
    print("Have a look at the table for yourself")  # for other teams

Bottom of the league. Unlucky Rothes


## 1.7 Functions
In this exercise I created a function that converted miles in kms. I then printed the results

In [5]:
def miles_to_kms(miles):  # defines a function that converts miles in kms
    return miles * 1.60934

x = miles_to_kms(20)  # stores function with 20 miles
print(x)  # prints the conversion of 20 miles into kms

32.1868


## 1.8 Create a script that generates a multiplication table
In this execise I created a script that created a multiplication table. I defined a range of 1 to 10 and then printed the results for different numbers

In [9]:
def multab(n):  # defines function that creates a multiplication table for any number
    for i in range(1, 11):  # for loop for numbers between 1 and 10
        print(n, "x", i, "=", n * i)  


multab(4)  # gives multiplication table for number 4 multiplied by number between 1 and 10
multab(7)
multab(9)

4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
4 x 10 = 40
7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70
9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81
9 x 10 = 90


## 1.9 Loops
In this exercise I created a list that gave the count for each lunch item using a for loop

In [6]:
lunch = ["Salad", "Salad", "Egg", "Beef", "Potato", "Tea", "Chicken", "Potato", "Potato", "Coffee"]  # creates lunch list with items

item_count = {}  # empty dictionary for item counts
for item in lunch:  # for loop for lunch items
    if item not in item_count:
        item_count[item] = 1  # if item is not in the dictionary then give it value of 1
    else:
        item_count[item] += 1  # otherwise, keep adding 1 to the value for that item in the dictionary

print(item_count)  # prints item count results

{'Salad': 2, 'Egg': 1, 'Beef': 1, 'Potato': 3, 'Tea': 1, 'Chicken': 1, 'Coffee': 1}


## 1.10 Read files
In this exercise I read in a dataset using pandas and print the 1st 30 rows of the dataset using head()

In [12]:
import pandas as pd  # imports library
df = pd.read_csv('/arcgis/home/Latest_earthquake_world.csv')  # loads in csv file using pandas
print(df.head(30))  # shows 1st 30 rows in the dataset

                        time   latitude   longitude    depth   mag magType  \
0   2023-02-23T08:01:02.881Z  38.128000   73.218400   10.000  4.70      mb   
1   2023-02-23T06:55:34.020Z  18.794600  -63.920500   10.000  3.67      md   
2   2023-02-23T06:50:49.137Z  38.487900   72.812200   10.000  4.50      mb   
3   2023-02-23T06:18:13.280Z  -8.548300  -77.625400   66.540  4.70      mb   
4   2023-02-23T03:36:09.429Z -18.287000 -177.826100  524.983  4.90      mb   
5   2023-02-23T03:18:57.663Z -30.391600  -71.685600   34.097  4.40      ml   
6   2023-02-23T02:18:00.671Z  38.336200   73.106700   10.000  4.70      mb   
7   2023-02-23T02:07:46.940Z  38.182200   73.234600   10.000  4.80      mb   
8   2023-02-23T02:03:42.690Z  18.079300  -68.088800   78.000  3.54      md   
9   2023-02-23T01:35:57.658Z  38.182400   73.279400   10.000  4.90      mb   
10  2023-02-23T01:33:25.965Z  59.261500 -153.135600   77.400  2.50      ml   
11  2023-02-23T01:06:05.337Z  38.180400   72.782900   10.000  4.

## Lab 2: NumPy and Pandas

## 2.0 Import numpy
I imported the python library numpy as np

In [13]:
import numpy as np  # imports library

## 2.1 Arrays
I created an array of 10 ones, and array of integers 1 to 20 and a 5x5 matrix of ones that are of the integer data type

In [14]:
array1 = np.ones(10)  # creates an array of 10 ones
print(array1)

array2 = np.arange(1, 21, dtype="int")  # creates an array of the integers 1 to 20
print(array2)

matrix1 = np.ones((5,5), dtype="int")  # creates a 5x5 matrix that is of the integer data type
print(matrix1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## 2.2
I used numpy to create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution and reshape the above array into shape (27,)

In [15]:
matrix_random = np.random.randn(3, 3, 3)  # creates a 3D matrix using randon numbers
print(matrix_random)

[[[-0.43443349  0.3700434   0.13695261]
  [ 0.29848465  0.91300822  0.42388002]
  [-2.25355311 -0.48207524 -0.07423373]]

 [[-0.18311374  1.38448407 -0.36813287]
  [ 0.55359542  1.65783592  0.02314055]
  [ 0.31494073 -0.92035568  1.67082348]]

 [[-0.70265854  1.79111842 -1.84176833]
  [ 0.30755452  1.4642728  -0.70530045]
  [-0.54883173  1.45272918 -2.03629315]]]


## 2.3
I created an array of 20 linearly spaced numbers between 1 and 10.

In [16]:
array1 = np.linspace(1, 10, 20,)  # creates an array of 20 linearly spaced numbers between 1 and 10
print(array1)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


## 2.4
I ran the following code to create an array of shape 5 x 5 and then use indexing to produce the outputs shown below

In [17]:
import numpy as np  # imports library
a = np.arange(1, 26).reshape(5, -1)  # creates a 5x5 array with the values 1 to 25
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [18]:
a = np.arange(1, 26).reshape(5, -1)
indexed = a[1:, 3:]  # selects row 2 and onwards and column 4 and onwards
print(indexed)

[[ 9 10]
 [14 15]
 [19 20]
 [24 25]]


In [19]:
a = np.arange(1, 26).reshape(5, -1)
indexed = a[1]  # selects the second row of the array (index 1)
print(indexed)

[ 6  7  8  9 10]


## 2.5
I calculated the sum of all the numbers in a

In [20]:
total = np.sum(a)  # calculates the sum of all the numbers in array "a"
print(total)

325


## 2.6
I calculated the sum of each row in a 

In [21]:
sum_rows = np.sum(a, axis=1)  # calculates the sum of each row in the array "a"
print(sum_rows)

[ 15  40  65  90 115]


## 2.7
I extracted all values of 'a' greater than the mean of 'a'

In [22]:
mean = np.mean(a)  # calculates the average of the array

mask = a > mean  # creates a boolean mask for the values that are greater than the mean of the array 

output = a[mask]  # extracts values of the array that are greater than the mean of the array
print(mean)  # prints the average
print(output)  # prints the values of the array that are greater than the mean of the array

13.0
[14 15 16 17 18 19 20 21 22 23 24 25]


## 2.8: Pandas
I imported the python library pandas as pd


In [9]:
import pandas as pd  # imports library

## 2.9
I imported a dataframe directly from a url and read it into the notebook

In [10]:
link = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv"  
df = pd.read_csv(link)  # loads the file using pandas


## 2.10
I identified how many rows and columns there were in the data frame


In [11]:
print(df.info())  # prints information about the dataframe
print(df.shape)  # prints the number of rows and columns in the dataframe
print(len(df))  # prints the number of rows in the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1430 entries, 0 to 1429
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   country        1430 non-null   object 
 1   food_category  1430 non-null   object 
 2   consumption    1430 non-null   float64
 3   co2_emmission  1430 non-null   float64
dtypes: float64(2), object(2)
memory usage: 44.8+ KB
None
(1430, 4)
1430


## 2.11
I identified the mean co2 emissions of the whole dataset

In [12]:
co2_mean = df["co2_emmission"].mean()  # calculates the mean co2 emissions in the whole dataset
print(co2_mean)  # prints the results

74.383993006993


## 2.12
I identified the maximum co2 emissions in the dataset and identified which food group it belonged to

In [13]:
max = df["co2_emmission"].max()  # identifies max co2 values in the dataset
print(max)
max_row = df.loc[df["co2_emmission"] == max]  # select rows where co2 emissions are of the max value
print(max_row[["food_category", "country", "co2_emmission"]])  # prints the max row for co2 while selecting the rows "food_category, "country" and "co2 emmissions"

1712.0
  food_category    country  co2_emmission
2          Beef  Argentina         1712.0


## 2.13
I identifed how many countries produced more than 1000 Kg CO2/person/year for at least one food type

In [14]:
mask = df["co2_emmission"] > 1000  # creates a boolean mask for the co2 values greater than 1000
countries = set(df.loc[mask, "country"])
print("countries:", countries)  # prints countries of co2 values greater than 1000
print("number of countries:", len(countries))  # prints the number of countries that produce more than 1000kg of co2/person/year for at least one food type

countries: {'Australia', 'Argentina', 'USA', 'Brazil', 'Bermuda'}
number of countries: 5


## 2.15
I identifed the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined

In [15]:
meat_items = ["Pork", "Poultry", "Fish", "Lamb & Goat", "Beef"]  # creates list of meat items
meat_items_df = df.query('food_category in @meat_items')  # filters the dataframe to include meat items from the list
total_emissions = meat_items_df["co2_emmission"].sum()  # calculates the total emissions from meat items 
print(total_emissions)  # prints the results

74441.13


## 2.16
I identifed the total emissions of all other (non-meat) products in the dataset combined

In [30]:
meat_items = ["Pork", "Poultry", "Fish", "Lamb & Goat", "Beef"]  # creates list of meat items
non_meat_items_df = df.query('food_category not in @meat_items')  # filters the dataframe to include only items not in the meat items list
total_emissions = non_meat_items_df["co2_emmission"].sum()  # calculates the total emission from non meat items
print(total_emissions)  # prints the results

31927.98
